AWSTemplateFormatVersion: "2010-09-09"
Description: Projeto de Conclusao da Disciplina eEDB-016/2024-2

Resources:

  TabelaCarrinho:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Carrinho
      AttributeDefinitions: 
        - AttributeName: "id_carrinho"
          AttributeType: "S"
        - AttributeName: "id_cliente"
          AttributeType: "S"
      KeySchema: 
        - AttributeName: "id_carrinho"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      GlobalSecondaryIndexes:
        - IndexName: "gsi_cliente"
          KeySchema:
            - AttributeName: "id_cliente"
              KeyType: "HASH"
          Projection:
            ProjectionType: "ALL"
          ProvisionedThroughput:
            ReadCapacityUnits: 5
            WriteCapacityUnits: 5
      Tags:
        - Key: "Projeto"
          Value: "Repositorio de Dados e NoSQL"

  TabelaListaDesejo:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ListaDesejo
      AttributeDefinitions: 
        - AttributeName: "id_lista_desejo"
          AttributeType: "S"
        - AttributeName: "id_cliente"
          AttributeType: "S"
        - AttributeName: "data_geracao"
          AttributeType: "S"
      KeySchema: 
        - AttributeName: "id_lista_desejo"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      GlobalSecondaryIndexes:
        - IndexName: "gsi_cliente"
          KeySchema:
            - AttributeName: "id_cliente"
              KeyType: "HASH"
            - AttributeName: "data_geracao"
              KeyType: "RANGE"
          Projection:
            ProjectionType: "ALL"
          ProvisionedThroughput:
            ReadCapacityUnits: 5
            WriteCapacityUnits: 5
      Tags:
        - Key: "Projeto"
          Value: "Repositorio de Dados e NoSQL"

  TabelaRecomendacao:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Recomendacao
      AttributeDefinitions: 
        - AttributeName: "id_recomendacao"
          AttributeType: "S"
        - AttributeName: "id_cliente"
          AttributeType: "S"
        - AttributeName: "data_geracao"
          AttributeType: "S"
      KeySchema: 
        - AttributeName: "id_recomendacao"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      GlobalSecondaryIndexes:
        - IndexName: "gsi_cliente"
          KeySchema:
            - AttributeName: "id_cliente"
              KeyType: "HASH"
            - AttributeName: "data_geracao"
              KeyType: "RANGE"
          Projection:
            ProjectionType: "ALL"
          ProvisionedThroughput:
            ReadCapacityUnits: 5
            WriteCapacityUnits: 5
      Tags:
        - Key: "Projeto"
          Value: "Repositorio de Dados e NoSQL"

  TabelaPedido:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Pedido
      AttributeDefinitions: 
        - AttributeName: "id_pedido"
          AttributeType: "S"
        - AttributeName: "id_carrinho"
          AttributeType: "S"
        - AttributeName: "id_cliente"
          AttributeType: "S"
        - AttributeName: "data_pedido"
          AttributeType: "S"
      KeySchema: 
        - AttributeName: "id_pedido"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      GlobalSecondaryIndexes:
        - IndexName: "gsi_carrinho"
          KeySchema:
            - AttributeName: "id_carrinho"
              KeyType: "HASH"
          Projection:
            ProjectionType: "ALL"
          ProvisionedThroughput:
            ReadCapacityUnits: 5
            WriteCapacityUnits: 5
        - IndexName: "gsi_cliente"
          KeySchema:
            - AttributeName: "id_cliente"
              KeyType: "HASH"
            - AttributeName: "data_pedido"
              KeyType: "RANGE"
          Projection:
            ProjectionType: "ALL"
          ProvisionedThroughput:
            ReadCapacityUnits: 5
            WriteCapacityUnits: 5
      Tags:
        - Key: "Projeto"
          Value: "Repositorio de Dados e NoSQL"

  TabelaCliente:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Cliente
      AttributeDefinitions: 
        - AttributeName: "id_cliente"
          AttributeType: "S"
      KeySchema: 
        - AttributeName: "id_cliente"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      Tags:
        - Key: "Projeto"
          Value: "Repositorio de Dados e NoSQL"

  TabelaProduto:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Produto
      AttributeDefinitions:
        - AttributeName: "id_produto"
          AttributeType: "S"
        - AttributeName: "id_parceiro"
          AttributeType: "S"
        - AttributeName: "preco"
          AttributeType: "N"
      KeySchema: 
        - AttributeName: "id_produto"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      GlobalSecondaryIndexes:
        - IndexName: "gsi_parceiro"
          KeySchema:
            - AttributeName: "id_parceiro"
              KeyType: "HASH"
            - AttributeName: "preco"
              KeyType: "RANGE"
          Projection:
            ProjectionType: "ALL"
          ProvisionedThroughput:
            ReadCapacityUnits: 5
            WriteCapacityUnits: 5
      Tags:
        - Key: "Projeto"
          Value: "Repositorio de Dados e NoSQL"